baseURL = 'https://zhichen-site.github.io/'
languageCode = 'en-us'
title = 'Zhichen Guo'
theme = 'hugo-theme-mini'

[params]
  author = 'Zhichen Guo'
  bio = 'Ph.D. Candidate in Psychometrics'
  description = 'Personal website of Zhichen Guo'
  enableGitalk = false
  enableRSS = false

  # Navigation
  [[menu.main]]
  name = "Home"
  url = "/"
  weight = 1

  [[menu.main]]
  name = "Posts"
  url = "/posts"
  weight = 2

  # 社交媒体链接
  [params.social]
  orcid = "https://orcid.org/0000-0002-9522-620X"