baseURL = 'https://zhichen-guo.com/'
languageCode = 'en-us'
title = 'Zhichen Guo'
theme = 'hugo-theme-mini'
googleAnalytics = 'G-ZTJ7N8EPRK'

[params]
  author = 'Zhichen Guo'
  bio = 'Ph.D. Candidate in Psychometrics'
  description = 'Personal website of Zhichen Guo'
  enableGitalk = false
  enableRSS = false
  showPowerBy = false

  # Navigation
  [[menu.main]]
  name = "Home"
  url = "/"
  weight = 1

  [[menu.main]]
  name = "Posts"
  url = "/posts"
  weight = 2

  # Social Media Links
  [params.social]
  orcid = "https://orcid.org/0000-0002-9522-620X"

  [params.gitalk]
  clientId = "Ov23lilPn2G9JI6IMIPd"
  clientSecret = "342cb51d45d65ce4c9a5e5bbf72529cb6f4bf319"
  repo = "my-academic-website"
  owner = "zhichen-hub"